### ISSUE TITLE
Provide as official Gnome Extension

### ISSUE THREAD

**Issue by valentingregoire** [swsnr/gnome-search-providers-jetbrains#52]
Could you provide this as a Gnome Extension to be installed in the usual way? Or at least for other distros?

**Comment by swsnr** [comment]
A GNOME extension would amount to a complete rewrite, which I have neither time nor motivation for.  Same goes for package formats of distributions I don't use.

This used to be a GNOME extension (see <https://github.com/swsnr/jetbrains-search-provider>), but it didn't survive the GNOME 40 release which broke just about everything.  It's better these days; GNOME 45 has proper modules, and added a more or less public API for search providers.  But it'd also be a major effort to port the entire extension to GNOME 45.   Feel free to resurrect it, if you prefer an extension. 

As for other packaging formats, do feel free to make a pull request which adds a Github workflow to build packages for other distributions, or make your own PPA/Copr/whatever.

Closing this, because it's not actionable to me.
